// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import RatingFormController from "./rating_form_controller"
application.register("rating-form", RatingFormController)

import RatingSummaryController from "./rating_summary_controller"
application.register("rating-summary", RatingSummaryController)

import ReviewController from "./review_controller"
application.register("review", ReviewController)
