// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import RatingController from "./rating_controller"
application.register("rating", RatingController)

import ReviewController from "./review_controller"
application.register("review", ReviewController)
